name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install deps
      run: sudo apt-get update && sudo apt-get install -y gcc-riscv64-unknown-elf

    - name: Build project
      run: make

    - name: Run tests
      run: make test
